language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 7.3
  - 7.4

services:
  - mysql

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1

before_script:
  - composer install
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: ./vendor/bin/phpunit
